name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24.0.1
      uses: actions/setup-java@v4
      with:
        java-version: '24.0.1'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install
